# Install command-line tools
# Usage: `brew bundle Brewfile`

tap homebrew/dupes
tap homebrew/versions
tap thoughtbot/formulae

install ack
install autoenv
install bash                        # add `/usr/local/bin/bash` to /etc/shells
install cabal-install
install coreutils                   # add `/usr/local/gnubin` to $PATH
install ctags
install diffutils
install dnsmasq
install expect
install findutils --default-names
install gawk
install git
install gnu-sed --default-names
install gnu-tar --default-names
install gnu-which --default-names
install grc
install grep --default-names
install gzip
install hub
install imagemagick --with-webp
install less
install lynx
# install mit-scheme                # install joseph.is/XQuartz first
install moreutils
install node                        # TODO switch to nvm
install openssh --with-brewed-openssl
install pv
install python --with-brewed-openssl
install rbenv
install rbenv-gem-rehash
install rcm
install reattach-to-user-namespace
install rename
install rlwrap
install ruby-build
install rsync
install the_silver_searcher
install tmux
install tree
install unzip
install vim --override-system-vi
install watch
install wdiff --with-gettext
install webkit2png
install wget --enable-iri
install xz
install z
install zsh                         # add `/usr/local/bin/zsh` to /etc/shells
