#!/bin/sh
# runs immediately after rcm

bold='\033[1m'
unbold='\033[0m'

# Vim - http://joseph.is/1sZma4R
if [ -d $HOME/.vim/bundle/Vundle.vim ]; then
    # checks if vimrc or vimrc.bundles changed in the last commit
    if [ -n "$(cd $HOME/.dotfiles; git diff HEAD^^ vimrc vimrc.bundles)" ]; then
        echo "\n${bold}Updating Vundle...${unbold}";
        cd $HOME/.vim/bundle/Vundle.vim; git pull
        echo "\n${bold}Installing Vundle Plugins...${unbold}";
        vim -u $HOME/.vimrc.bundles +PluginInstall +PluginClean! +qall
    fi
fi

echo "\nDone."

