#!/bin/sh

bold='\033[1m'
unbold='\033[0m'

# Required directories
ln -sf $HOME/.bin $HOME/bin &>/dev/null
mkdir -p $HOME/Projects 2>/dev/null
mkdir -p $HOME/tmp 2>/dev/null

# Homebrew - http://brew.sh/
echo "\n${bold}Updating Homebrew formulas...${unbold}"
brew update
echo "\n${bold}Upgrading installed brews...${unbold}"
brew upgrade
echo "\n${bold}Remove unneeded brews...${unbold}"
brew cleanup

# Zsh Syntax Highlighting - http://joseph.is/1yPtYtq
if [ -d $HOME/.zsh/custom/plugins/zsh-syntax-highlighting ]; then
    echo "\n${bold}Updating Zsh Syntax Highlighting...${unbold}";
    cd $HOME/.zsh/custom/plugins/zsh-syntax-highlighting; git pull
else
    echo "\n${bold}Installing Zsh Syntax Highlighting...${unbold}";
    git clone https://github.com/zsh-users/zsh-syntax-highlighting.git \
        $HOME/.zsh/custom/plugins/zsh-syntax-highlighting
fi

# Base16 color scheme - http://joseph.is/11RoQHA
if [ -d $HOME/.config/base16-iterm2 ]; then
    echo "\n${bold}Updating Base16 iTerm2 color scheme...${unbold}";
    cd $HOME/.config/base16-iterm2; git pull
else
    echo "\n${bold}Installing Base16 iTerm2 color scheme...${unbold}";
    git clone https://github.com/chriskempson/base16-iterm2.git $HOME/.config/base16-iterm2
fi
if [ -d $HOME/.config/base16-shell ]; then
    echo "\n${bold}Updating Base16 shell color scheme...${unbold}";
    cd $HOME/.config/base16-shell; git pull
else
    echo "\n${bold}Installing Base16 shell color scheme...${unbold}";
    git clone https://github.com/chriskempson/base16-shell.git $HOME/.config/base16-shell
fi

# JavaScript - https://www.npmjs.org/doc/
if [ ! $(which grunt) ]; then
    echo "\n${bold}Installing Grunt...${unbold}";
    npm install -g grunt-cli
fi
if [ ! $(which gulp) ]; then
    echo "\n${bold}Installing Gulp...${unbold}";
    npm install -g gulp
fi

# PHP - https://getcomposer.org
if [ ! $(which composer) ]; then
    echo "\n${bold}Installing Composer...${unbold}";
    curl -sS https://getcomposer.org/installer | php
    mv composer.phar /usr/local/bin/composer
fi
echo "\n${bold}Updating Composer...${unbold}";
composer self-update
composer global update

# Wordpress Coding Standards - http://joseph.is/1wdO6SC
if [ -d $HOME/.config/WordPress-Coding-Standards ]; then
    echo "\n${bold}Updating WordPress Coding Standards...${unbold}";
    cd $HOME/.config/WordPress-Coding-Standards; git pull
else
    echo "\n${bold}Installing WordPress Coding Standards...${unbold}";
    git clone -b master https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards.git \
        $HOME/.config/WordPress-Coding-Standards
    echo "\n${bold}Adding WordPress to PHP Code Sniffer Standards...${unbold}";
    $HOME/.composer/vendor/bin/phpcs --config-set installed_paths $HOME/.config/WordPress-Coding-Standards
    $HOME/.composer/vendor/bin/phpcs -i
fi

# Vim - http://joseph.is/1sZma4R
mkdir -p $HOME/.vim/undo 2>/dev/null
if [ -d $HOME/.vim/bundle/Vundle.vim ]; then
    echo "\n${bold}Updating Vundle...${unbold}";
    cd $HOME/.vim/bundle/Vundle.vim; git pull
else
    echo "\n${bold}Installing Vundle...${unbold}";
    git clone https://github.com/gmarik/Vundle.vim.git $HOME/.vim/bundle/Vundle.vim
fi
echo "\n${bold}Installing/upgrading Vundle Plugins...${unbold}";
vim -u $HOME/.vimrc.bundles +PluginInstall +PluginClean! +qa

echo "\nDone."
