#!/bin/sh
# runs right before rcm

bold='\033[1m'
unbold='\033[0m'

# Update dotfiles
echo "\n${bold}Fetching dotfiles from GitHub...${unbold}"
cd $HOME/.dotfiles; git pull

echo "\n${bold}Syncing dotfiles to ${HOME}/...${unbold}"
