#!/bin/sh
# runs right before rcm

bold='\033[1m'
unbold='\033[0m'

# Update dotfiles
echo "\n${bold}Updating dotfiles...${unbold}"
cd $HOME/.dotfiles; git pull

# Oh My Zsh
if [ -z "$ZSH" ]; then
    echo "\n${bold}Install Oh My Zsh...${unbold}"
    curl -L http://install.ohmyz.sh | ZSH=$HOME/.zsh sh
fi

echo ""
