#!/bin/sh
# install all the things

bold='\033[1m'
unbold='\033[0m'

# Make common directories
mkdir -p $HOME/tmp 2>/dev/null
mkdir -p $HOME/Projects 2>/dev/null
ln -sf $HOME/.bin $HOME/bin &>/dev/null
[ -e $HOME/Dropbox ] && mkdir -p $HOME/Dropbox/.tmuxinator 2>/dev/null && ln -shf $HOME/Dropbox/.tmuxinator/ $HOME/.tmuxinator
[ -e $HOME/Dropbox ] && mkdir -p $HOME/Dropbox/.karabiner 2>/dev/null && ln -shf $HOME/Dropbox/.karabiner/ $HOME/.config/karabiner
mkdir -p $HOME/.nvm 2>/dev/null
ln -shf `brew --prefix nvm`/nvm-exec $HOME/.nvm/nvm-exec
ln -shf `brew --prefix nvm`/nvm.sh $HOME/.nvm/nvm.sh

# Install Homebrew
echo "\n${bold}Installing Brew packages...${unbold}"
brew bundle --file=$HOME/.dotfiles/Brewfile

# Set sensible hacker defaults for macOS
echo "\n${bold}Setting sensible hacker defaults...${unbold}"
$HOME/.dotfiles/scripts/osx

# Oh My Zsh
echo "\n${bold}Install Oh My Zsh...${unbold}"
curl -L http://install.ohmyz.sh | ZSH=$HOME/.zsh sh

# Zsh Syntax Highlighting - http://joseph.is/1yPtYtq
echo "\n${bold}Installing Zsh Syntax Highlighting...${unbold}"
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git \
    $HOME/.zsh/custom/plugins/zsh-syntax-highlighting

# Base16 color scheme - http://joseph.is/11RoQHA
echo "\n${bold}Installing Base16 iTerm2 color scheme...${unbold}"
git clone https://github.com/chriskempson/base16-iterm2.git $HOME/.config/base16-iterm2
echo "\n${bold}Installing Base16 shell color scheme...${unbold}"
git clone https://github.com/chriskempson/base16-shell.git $HOME/.config/base16-shell
echo "\n${bold}Installing Base16 Mutt color scheme...${unbold}"
git clone https://github.com/josephholsten/base16-mutt.git $HOME/.config/base16-mutt

# Vim - http://joseph.is/1sZma4R
echo "\n${bold}Installing Vundle...${unbold}"
git clone https://github.com/gmarik/Vundle.vim.git $HOME/.vim/bundle/Vundle.vim
echo "\n${bold}Installing Vundle Plugins...${unbold}"
vim -u $HOME/.vimrc.bundles +PluginInstall +PluginClean! +qa < /dev/tty > /dev/tty

echo "\nDone."
